[package]
name = "sp105e-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
sp105e = { path = "../sp105e", features = [ "client", "clap" ]}
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
